export const OfferIdentity: SignApi.Identity = "OFFER"      // 提议者身份
export const AnswerIdentity: SignApi.Identity = "ANSWER"     // 应答者身份
export const ControllerIdentity: SignApi.Identity = "CONTROLLER" // 控制器身份
export const JoinCmd: SignApi.Command = "JOIN"       // 加入消息
export const OfferCmd: SignApi.Command = "OFFER"      // offer消息
export const AnswerCmd: SignApi.Command = "ANSWER"     // answer消息
export const CandidateCmd: SignApi.Command = "CANDIDATE"  // candidate消息
export const LeaveCmd: SignApi.Command = "LEAVE"      // 退出消息
export const ErrorCmd: SignApi.Command = "ERROR"      // 异常消息
export const MonitorCmd: SignApi.Command = "MONITOR" // 监控消息
export const RunInfoCmd: SignApi.Command = "RUN_INFO" // 运行时信息
export const ControllerCmd: SignApi.Command = "CONTROLLER" // 控制消息
export const OnJoin: SignApi.Emit = "OnJoin"
export const OnError: SignApi.Emit = "OnError"
export const OnAddStream: SignApi.Emit = "OnAddStream"
export const OnAnswerLevel: SignApi.Emit = "OnAnswerLevel"
export const OnMonitor: SignApi.Emit = "OnMonitor"
export const OnRunInfo: SignApi.Emit = "OnRunInfo"